export const questions = [
    { question: 'Woraus besteht ein Diamant?', answer: 'Kohlenstoff' },
    { question: 'Mit wie vielen Figuren startet ein Schachspiel?', answer: '32' },
    { question: 'Wer schrieb die Novelle "Der Schimmelreiter"?', answer: 'Theodor Storm' },
    { question: 'Was ist die Hauptstadt von Frankreich?', answer: 'Paris' },
    { question: 'Wie viele Planeten gibt es in unserem Sonnensystem?', answer: '8' },
    { question: 'Was ist die chemische Formel für Wasser?', answer: 'H2O' },
    { question: 'Wer malte die Mona Lisa?', answer: 'Leonardo da Vinci' },
    { question: 'Wie viele Bundesländer hat Deutschland?', answer: '16' },
    { question: 'Wer entdeckte Penicillin?', answer: 'Alexander Fleming' },
    { question: 'In welcher Stadt bist du, wenn du auf der Spanischen Treppe stehst?', answer: 'Rom' },
    { question: 'Wie lautet der 4. Buchstabe des griechischen Alphabets?', answer: 'Delta' },
    { question: 'Wie viele Punkte hat ein Würfel insgesamt?', answer: '42' },
    { question: 'In welcher Hauptstadt steht die Statue der kleinen Meerjungfrau?', answer: 'Kopenhagen' },
    { question: 'Wer war der erste Präsident der Vereinigten Staaten von Amerika?', answer: 'George Washington' },
    { question: 'Wer komponierte „Die Zauberflöte“?', answer: 'Wolfgang Amadeus Mozart' },
    { question: 'Wie lang ist die Strecke eines Marathons?', answer: '42,195km' },
    { question: 'Wie viele Tasten hat ein Klavier?', answer: '88' },
    { question: 'In welchem Jahr fiel die Berliner Mauer?', answer: '1989' },
    { question: 'Wie viele Beine hat eine Spinne?', answer: '8' },
    { question: 'Welche Farbe bekommst du, wenn du blau und gelb mischst?', answer: 'Grün' },
    { question: 'Mit wem geht Goethes „Faust“ einen Pakt ein?', answer: 'Mephisto' },
    { question: 'Wie heißt der Honigwein, der gerne von den Wikingern getrunken wurde?', answer: 'Met' },
    { question: 'Wer schrieb das Buch „1984“?', answer: 'George Orwell' },
    { question: 'Wie viele Kontinente gibt es auf der Erde?', answer: '7' },
    { question: 'Wie nennt man die Verwandlung einer Raupe zum Schmetterling?', answer: 'Metamorphose' },
    { question: 'In welchem Jahr wurde die Berliner Mauer errichtet?', answer: '1961' },
    { question: 'Wer war der Gründer von Apple Inc.?', answer: 'Steve Jobs' },
    { question: 'Welches Element hat das chemische Symbol „Fe“?', answer: 'Eisen' },
    { question: 'In welchem Jahr wurde der Euro als offizielle Währung in Europa eingeführt?', answer: '2002' },
    { question: 'Toms Mutter hat drei Kinder: Tick, Trick und … ?', answer: 'Tom' }
];